M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date Wed 31 May 2023 11:12:11 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-31T11:12:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X5.775Y-4.105
X5.775Y-4.505
T2
X6.5491Y-3.525
T3
X5.775Y-4.305
T0
M30
